# Generated by Django 6.0.3 on 2026-03-20 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Configuration Nationale', max_length=100)),
                ('required_points', models.PositiveIntegerField(default=12, verbose_name='Quota de présences')),
                ('period_days', models.PositiveIntegerField(default=180, verbose_name="Période d'observation (jours)")),
                ('absence_alert_days', models.PositiveIntegerField(default=30, verbose_name='Seuil Alerte Absence (jours)')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ville/District')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'Église")),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='church.location')),
            ],
            options={
                'verbose_name_plural': 'Églises',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant')], max_length=1, verbose_name='Genre (H/F/E)')),
                ('status', models.CharField(choices=[('VISITOR', 'Visiteur'), ('REGULAR', 'Membre Actif')], default='VISITOR', max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='church.church')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pointage', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Suivi effectué')),
                ('notes', models.TextField(blank=True, verbose_name='Note de visite')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='church.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.member')),
            ],
            options={
                'verbose_name_plural': "Alertes d'absence",
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN_CHURCH', 'Administrateur'), ('AGENT', 'Agent de Saisie')], default='AGENT', max_length=20)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pointage', models.DateField(default=django.utils.timezone.now)),
                ('theme_culte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thème du culte')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='church.member')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'unique_together': {('member', 'date_pointage')},
            },
        ),
    ]
