# Generated by Django 6.0.3 on 2026-03-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
            ],
            options={
                'verbose_name': '✅ Pointage/Présence',
                'verbose_name_plural': '✅ Pointages/Présences',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CulteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Thème du message')),
                ('date', models.DateTimeField(verbose_name='Date et Heure')),
                ('officiant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Officiant/Prédicateur')),
            ],
            options={
                'verbose_name': '✝️ Session de Culte',
                'verbose_name_plural': '✝️ Sessions de Culte',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CulteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type de Culte')),
            ],
            options={
                'verbose_name': '📖 Type de Culte',
                'verbose_name_plural': '📖 Types de Cultes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='member',
        ),
        migrations.AlterModelOptions(
            name='absencealert',
            options={'ordering': ['-created_at'], 'verbose_name': "⚠️ Alerte d'Absence", 'verbose_name_plural': "⚠️ Alertes d'Absences"},
        ),
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['location', 'name'], 'verbose_name': '🏛️ Église Locale', 'verbose_name_plural': '🏛️ Églises Locales'},
        ),
        migrations.AlterModelOptions(
            name='growthconfig',
            options={'verbose_name': 'Paramètre de Croissance', 'verbose_name_plural': '⚙️ Paramètres de Croissance'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': '📍 Département', 'verbose_name_plural': '📍 Départements du Congo'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['church', 'last_name', 'first_name'], 'verbose_name': '🙏 Membre/Fidèle', 'verbose_name_plural': '🙏 Membres/Fidèles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '👤 Profil Utilisateur', 'verbose_name_plural': '👤 Profils Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='absencealert',
            name='last_pointage',
        ),
        migrations.RemoveField(
            model_name='absencealert',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='growthconfig',
            name='absence_alert_days',
        ),
        migrations.RemoveField(
            model_name='growthconfig',
            name='period_days',
        ),
        migrations.RemoveField(
            model_name='growthconfig',
            name='required_points',
        ),
        migrations.AddField(
            model_name='absencealert',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière présence'),
        ),
        migrations.AddField(
            model_name='absencealert',
            name='pastoral_notes',
            field=models.TextField(blank=True, verbose_name='Notes du suivi pastoral'),
        ),
        migrations.AddField(
            model_name='growthconfig',
            name='absence_limit_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Seuil alerte absence (jours)'),
        ),
        migrations.AddField(
            model_name='growthconfig',
            name='promotion_days',
            field=models.PositiveIntegerField(default=90, verbose_name='Période promotion (jours)'),
        ),
        migrations.AddField(
            model_name='growthconfig',
            name='required_attendances',
            field=models.PositiveIntegerField(default=3, verbose_name='Présences requises'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='absencealert',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='church.church', verbose_name='Église'),
        ),
        migrations.AlterField(
            model_name='absencealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='absencealert',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Visite/Appel effectué'),
        ),
        migrations.AlterField(
            model_name='absencealert',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.member', verbose_name='Membre absent'),
        ),
        migrations.AlterField(
            model_name='growthconfig',
            name='label',
            field=models.CharField(default='Configuration Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonnée pour le zoom Map', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonnée pour le zoom Map', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='member',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('VISITOR', 'Visiteur'), ('REGULAR', 'Membre Actif')], default='VISITOR', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN_CHURCH', "Administrateur d'Église"), ('AGENT', 'Agent de Saisie')], default='AGENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='absencealert',
            index=models.Index(fields=['church', 'is_resolved'], name='church_abse_church__7bb1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='absencealert',
            index=models.Index(fields=['is_resolved', '-created_at'], name='church_abse_is_reso_e77ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'status'], name='church_memb_church__095897_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status', 'genre'], name='church_memb_status_621039_idx'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='church.member', verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='cultesession',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultes', to='church.church', verbose_name='Église'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='culte_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='church.cultesession', verbose_name='Session de culte'),
        ),
        migrations.AddField(
            model_name='cultesession',
            name='culte_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.cultetype', verbose_name='Type de culte'),
        ),
        migrations.DeleteModel(
            name='Pointage',
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['culte_session', '-recorded_at'], name='church_atte_culte_s_552fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', '-recorded_at'], name='church_atte_member__0d189d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('culte_session', 'member')},
        ),
        migrations.AddIndex(
            model_name='cultesession',
            index=models.Index(fields=['church', '-date'], name='church_cult_church__88d864_idx'),
        ),
        migrations.AddIndex(
            model_name='cultesession',
            index=models.Index(fields=['date'], name='church_cult_date_999690_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cultesession',
            unique_together={('church', 'culte_type', 'date')},
        ),
    ]
