# Generated by Django 6.0.3 on 2026-03-21 18:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_attendance_cultesession_cultetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de carte')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name="Date d'émission")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expirée'), ('LOST', 'Perdue')], default='ACTIVE', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='church.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': '🪪 Carte de Membre',
                'verbose_name_plural': '🪪 Cartes de Membre',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='church_card_member__c2d35d_idx'), models.Index(fields=['card_number'], name='church_card_card_nu_40cc8d_idx')],
            },
        ),
    ]
